###
GET http://localhost:4000/product/

###
GET http://localhost:4000/product/615c5aa707b15afb6152ab14

###
POST http://localhost:4000/product/
Content-Type: application/json

{
    "name": "usb",
    "price": 15,
    "stock": 100,
    "description": "aaaa",
    "category": "Electronica",
    "imagePath": "..." 
}

###
DELETE http://localhost:4000/product/6163b82f9ac99cc56a1c823b

###
PUT http://localhost:4000/product/615c60f6a55b741f41ec60f1
Content-Type: application/json

{
    "quantity": 110
}


###
POST http://localhost:4000/user/signup
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "12345678",
    "profile": "user"
}

###
POST http://localhost:4000/user/signin
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "12345678"
}

###
GET http://localhost:4000/user

###
GET http://localhost:4000/user/token

###
DELETE http://localhost:4000/user/615db83023a0b13406c7770f


###
POST http://localhost:4000/user/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345678"
}

###
GET http://localhost:4000/cart/

###
GET http://localhost:4000/cart/615db83023a0b13406c77711

###
POST http://localhost:4000/cart/
Content-Type: application/json

{
    "product": {
        "_id": "615db83023a0b13406c77711",
        "name": "keyboard",
        "price": 150,
        "quantity": 1,
        "imagePath": "photos/e2bb7724-4eed-467a-960e-719162e022d3.jpeg",
        "createdAt": "2021-10-05T12:57:49.888Z",
        "updatedAt": "2021-10-05T13:53:22.344Z"
    },
    "cartID": "615db83023a0b13406c77711"
}

###
PUT http://localhost:4000/cart/
Content-Type: application/json

{
    "cartID": "615db83023a0b13406c77711"
}

###
DELETE http://localhost:4000/cart/615d051226afb000d11eb2b1

###
POST http://localhost:4000/payment